apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: thanos-operator
    app.kubernetes.io/instance: thanosquery-editor-role
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/part-of: thanos-operator
  name: thanos-operator-thanosquery-editor-role
rules:
- apiGroups:
  - monitoring.thanos.io
  resources:
  - thanosqueries
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - monitoring.thanos.io
  resources:
  - thanosqueries/status
  verbs:
  - get
