apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: thanos-operator
    app.kubernetes.io/instance: controller-manager-sa
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name: serviceaccount
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/part-of: thanos-operator
  name: {{ include "thanos-operator.resourceName" (dict "suffix" "controller-manager" "context" $) }}
  namespace: {{ .Release.Namespace }}
