{{- if .Values.metrics.enable }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/component: metrics
    app.kubernetes.io/created-by: thanos-operator
    app.kubernetes.io/instance: metrics-auth-role
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name: clusterrole
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/part-of: thanos-operator
  name: {{ include "thanos-operator.resourceName" (dict "suffix" "metrics-auth-role" "context" $) }}
rules:
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
{{- end }}
