# permissions for end users to view thanosreceiverouters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: thanos-operator
    app.kubernetes.io/managed-by: kustomize
  name: thanosreceiverouter-viewer-role
rules:
- apiGroups:
  - monitoring.thanos.io
  resources:
  - thanosreceiverouters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - monitoring.thanos.io
  resources:
  - thanosreceiverouters/status
  verbs:
  - get
