apiVersion: monitoring.thanos.io/v1alpha1
kind: ThanosRuler
metadata:
  name: example-ruler
spec:
  alertmanagerURL: http://alertmanager.example.com:9093
  evaluationInterval: 1m
  imagePullPolicy: IfNotPresent
  logFormat: logfmt
  queryLabelSelector:
    matchLabels:
      app.kubernetes.io/part-of: thanos
      operator.thanos.io/query-api: "true"
  replicas: 1
  ruleConfigSelector:
    matchLabels:
      operator.thanos.io/prometheus-rule: "true"
  rulerMode:
    stateful:
      externalLabels:
        rule_replica: $(NAME)
      objectStorageConfig:
        key: thanos.yaml
        name: thanos-object-storage
      retention: 2h
    type: Stateful
  storage:
    size: 1Gi
status: {}
