//go:build !ignore_autogenerated

/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	corev1 "k8s.io/api/core/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Additional) DeepCopyInto(out *Additional) {
	*out = *in
	if in.Args != nil {
		in, out := &in.Args, &out.Args
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Containers != nil {
		in, out := &in.Containers, &out.Containers
		*out = make([]corev1.Container, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Volumes != nil {
		in, out := &in.Volumes, &out.Volumes
		*out = make([]corev1.Volume, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.VolumeMounts != nil {
		in, out := &in.VolumeMounts, &out.VolumeMounts
		*out = make([]corev1.VolumeMount, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Ports != nil {
		in, out := &in.Ports, &out.Ports
		*out = make([]corev1.ContainerPort, len(*in))
		copy(*out, *in)
	}
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make([]corev1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ServicePorts != nil {
		in, out := &in.ServicePorts, &out.ServicePorts
		*out = make([]corev1.ServicePort, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Additional.
func (in *Additional) DeepCopy() *Additional {
	if in == nil {
		return nil
	}
	out := new(Additional)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BlockConfig) DeepCopyInto(out *BlockConfig) {
	*out = *in
	if in.BlockFilesConcurrency != nil {
		in, out := &in.BlockFilesConcurrency, &out.BlockFilesConcurrency
		*out = new(int32)
		**out = **in
	}
	if in.BlockMetaFetchConcurrency != nil {
		in, out := &in.BlockMetaFetchConcurrency, &out.BlockMetaFetchConcurrency
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BlockConfig.
func (in *BlockConfig) DeepCopy() *BlockConfig {
	if in == nil {
		return nil
	}
	out := new(BlockConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BlockViewerGlobalSyncConfig) DeepCopyInto(out *BlockViewerGlobalSyncConfig) {
	*out = *in
	if in.BlockViewerGlobalSyncInterval != nil {
		in, out := &in.BlockViewerGlobalSyncInterval, &out.BlockViewerGlobalSyncInterval
		*out = new(Duration)
		**out = **in
	}
	if in.BlockViewerGlobalSyncTimeout != nil {
		in, out := &in.BlockViewerGlobalSyncTimeout, &out.BlockViewerGlobalSyncTimeout
		*out = new(Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BlockViewerGlobalSyncConfig.
func (in *BlockViewerGlobalSyncConfig) DeepCopy() *BlockViewerGlobalSyncConfig {
	if in == nil {
		return nil
	}
	out := new(BlockViewerGlobalSyncConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CacheConfig) DeepCopyInto(out *CacheConfig) {
	*out = *in
	if in.InMemoryCacheConfig != nil {
		in, out := &in.InMemoryCacheConfig, &out.InMemoryCacheConfig
		*out = new(InMemoryCacheConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.ExternalCacheConfig != nil {
		in, out := &in.ExternalCacheConfig, &out.ExternalCacheConfig
		*out = new(corev1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CacheConfig.
func (in *CacheConfig) DeepCopy() *CacheConfig {
	if in == nil {
		return nil
	}
	out := new(CacheConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CommonFields) DeepCopyInto(out *CommonFields) {
	*out = *in
	if in.Version != nil {
		in, out := &in.Version, &out.Version
		*out = new(string)
		**out = **in
	}
	if in.Image != nil {
		in, out := &in.Image, &out.Image
		*out = new(string)
		**out = **in
	}
	if in.ImagePullPolicy != nil {
		in, out := &in.ImagePullPolicy, &out.ImagePullPolicy
		*out = new(corev1.PullPolicy)
		**out = **in
	}
	if in.ImagePullSecrets != nil {
		in, out := &in.ImagePullSecrets, &out.ImagePullSecrets
		*out = make([]corev1.LocalObjectReference, len(*in))
		copy(*out, *in)
	}
	if in.ResourceRequirements != nil {
		in, out := &in.ResourceRequirements, &out.ResourceRequirements
		*out = new(corev1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	if in.LogLevel != nil {
		in, out := &in.LogLevel, &out.LogLevel
		*out = new(string)
		**out = **in
	}
	if in.LogFormat != nil {
		in, out := &in.LogFormat, &out.LogFormat
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CommonFields.
func (in *CommonFields) DeepCopy() *CommonFields {
	if in == nil {
		return nil
	}
	out := new(CommonFields)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CompactConfig) DeepCopyInto(out *CompactConfig) {
	*out = *in
	if in.CompactConcurrency != nil {
		in, out := &in.CompactConcurrency, &out.CompactConcurrency
		*out = new(int32)
		**out = **in
	}
	if in.BlockFetchConcurrency != nil {
		in, out := &in.BlockFetchConcurrency, &out.BlockFetchConcurrency
		*out = new(int32)
		**out = **in
	}
	if in.CleanupInterval != nil {
		in, out := &in.CleanupInterval, &out.CleanupInterval
		*out = new(Duration)
		**out = **in
	}
	if in.ConsistencyDelay != nil {
		in, out := &in.ConsistencyDelay, &out.ConsistencyDelay
		*out = new(Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CompactConfig.
func (in *CompactConfig) DeepCopy() *CompactConfig {
	if in == nil {
		return nil
	}
	out := new(CompactConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DebugConfig) DeepCopyInto(out *DebugConfig) {
	*out = *in
	if in.AcceptMalformedIndex != nil {
		in, out := &in.AcceptMalformedIndex, &out.AcceptMalformedIndex
		*out = new(bool)
		**out = **in
	}
	if in.MaxCompactionLevel != nil {
		in, out := &in.MaxCompactionLevel, &out.MaxCompactionLevel
		*out = new(int32)
		**out = **in
	}
	if in.HaltOnError != nil {
		in, out := &in.HaltOnError, &out.HaltOnError
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DebugConfig.
func (in *DebugConfig) DeepCopy() *DebugConfig {
	if in == nil {
		return nil
	}
	out := new(DebugConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DownsamplingConfig) DeepCopyInto(out *DownsamplingConfig) {
	*out = *in
	if in.Disable != nil {
		in, out := &in.Disable, &out.Disable
		*out = new(bool)
		**out = **in
	}
	if in.Concurrency != nil {
		in, out := &in.Concurrency, &out.Concurrency
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DownsamplingConfig.
func (in *DownsamplingConfig) DeepCopy() *DownsamplingConfig {
	if in == nil {
		return nil
	}
	out := new(DownsamplingConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExternalLabelShardingConfig) DeepCopyInto(out *ExternalLabelShardingConfig) {
	*out = *in
	if in.Values != nil {
		in, out := &in.Values, &out.Values
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExternalLabelShardingConfig.
func (in *ExternalLabelShardingConfig) DeepCopy() *ExternalLabelShardingConfig {
	if in == nil {
		return nil
	}
	out := new(ExternalLabelShardingConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in ExternalLabels) DeepCopyInto(out *ExternalLabels) {
	{
		in := &in
		*out = make(ExternalLabels, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExternalLabels.
func (in ExternalLabels) DeepCopy() ExternalLabels {
	if in == nil {
		return nil
	}
	out := new(ExternalLabels)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FeatureGates) DeepCopyInto(out *FeatureGates) {
	*out = *in
	if in.ServiceMonitorConfig != nil {
		in, out := &in.ServiceMonitorConfig, &out.ServiceMonitorConfig
		*out = new(ServiceMonitorConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.PrometheusRuleEnabled != nil {
		in, out := &in.PrometheusRuleEnabled, &out.PrometheusRuleEnabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FeatureGates.
func (in *FeatureGates) DeepCopy() *FeatureGates {
	if in == nil {
		return nil
	}
	out := new(FeatureGates)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InMemoryCacheConfig) DeepCopyInto(out *InMemoryCacheConfig) {
	*out = *in
	if in.MaxSize != nil {
		in, out := &in.MaxSize, &out.MaxSize
		*out = new(StorageSize)
		**out = **in
	}
	if in.MaxItemSize != nil {
		in, out := &in.MaxItemSize, &out.MaxItemSize
		*out = new(StorageSize)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InMemoryCacheConfig.
func (in *InMemoryCacheConfig) DeepCopy() *InMemoryCacheConfig {
	if in == nil {
		return nil
	}
	out := new(InMemoryCacheConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IndexHeaderConfig) DeepCopyInto(out *IndexHeaderConfig) {
	*out = *in
	if in.EnableLazyReader != nil {
		in, out := &in.EnableLazyReader, &out.EnableLazyReader
		*out = new(bool)
		**out = **in
	}
	if in.LazyReaderIdleTimeout != nil {
		in, out := &in.LazyReaderIdleTimeout, &out.LazyReaderIdleTimeout
		*out = new(Duration)
		**out = **in
	}
	if in.LazyDownloadStrategy != nil {
		in, out := &in.LazyDownloadStrategy, &out.LazyDownloadStrategy
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IndexHeaderConfig.
func (in *IndexHeaderConfig) DeepCopy() *IndexHeaderConfig {
	if in == nil {
		return nil
	}
	out := new(IndexHeaderConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IngesterHashringSpec) DeepCopyInto(out *IngesterHashringSpec) {
	*out = *in
	in.CommonFields.DeepCopyInto(&out.CommonFields)
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.ExternalLabels != nil {
		in, out := &in.ExternalLabels, &out.ExternalLabels
		*out = make(ExternalLabels, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	out.TSDBConfig = in.TSDBConfig
	if in.ObjectStorageConfig != nil {
		in, out := &in.ObjectStorageConfig, &out.ObjectStorageConfig
		*out = new(ObjectStorageConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.TenancyConfig != nil {
		in, out := &in.TenancyConfig, &out.TenancyConfig
		*out = new(TenancyConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.AsyncForwardWorkerCount != nil {
		in, out := &in.AsyncForwardWorkerCount, &out.AsyncForwardWorkerCount
		*out = new(uint64)
		**out = **in
	}
	if in.StoreLimitsOptions != nil {
		in, out := &in.StoreLimitsOptions, &out.StoreLimitsOptions
		*out = new(StoreLimitsOptions)
		**out = **in
	}
	if in.TooFarInFutureTimeWindow != nil {
		in, out := &in.TooFarInFutureTimeWindow, &out.TooFarInFutureTimeWindow
		*out = new(Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IngesterHashringSpec.
func (in *IngesterHashringSpec) DeepCopy() *IngesterHashringSpec {
	if in == nil {
		return nil
	}
	out := new(IngesterHashringSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IngesterSpec) DeepCopyInto(out *IngesterSpec) {
	*out = *in
	in.DefaultObjectStorageConfig.DeepCopyInto(&out.DefaultObjectStorageConfig)
	if in.Hashrings != nil {
		in, out := &in.Hashrings, &out.Hashrings
		*out = make([]IngesterHashringSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.Additional.DeepCopyInto(&out.Additional)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IngesterSpec.
func (in *IngesterSpec) DeepCopy() *IngesterSpec {
	if in == nil {
		return nil
	}
	out := new(IngesterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObjectStorageConfig) DeepCopyInto(out *ObjectStorageConfig) {
	*out = *in
	out.LocalObjectReference = in.LocalObjectReference
	if in.Optional != nil {
		in, out := &in.Optional, &out.Optional
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObjectStorageConfig.
func (in *ObjectStorageConfig) DeepCopy() *ObjectStorageConfig {
	if in == nil {
		return nil
	}
	out := new(ObjectStorageConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QueryFrontendSpec) DeepCopyInto(out *QueryFrontendSpec) {
	*out = *in
	in.CommonFields.DeepCopyInto(&out.CommonFields)
	if in.QueryLabelSelector != nil {
		in, out := &in.QueryLabelSelector, &out.QueryLabelSelector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.LogQueriesLongerThan != nil {
		in, out := &in.LogQueriesLongerThan, &out.LogQueriesLongerThan
		*out = new(Duration)
		**out = **in
	}
	if in.QueryRangeResponseCacheConfig != nil {
		in, out := &in.QueryRangeResponseCacheConfig, &out.QueryRangeResponseCacheConfig
		*out = new(CacheConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.QueryRangeSplitInterval != nil {
		in, out := &in.QueryRangeSplitInterval, &out.QueryRangeSplitInterval
		*out = new(Duration)
		**out = **in
	}
	if in.LabelsSplitInterval != nil {
		in, out := &in.LabelsSplitInterval, &out.LabelsSplitInterval
		*out = new(Duration)
		**out = **in
	}
	if in.LabelsDefaultTimeRange != nil {
		in, out := &in.LabelsDefaultTimeRange, &out.LabelsDefaultTimeRange
		*out = new(Duration)
		**out = **in
	}
	in.Additional.DeepCopyInto(&out.Additional)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QueryFrontendSpec.
func (in *QueryFrontendSpec) DeepCopy() *QueryFrontendSpec {
	if in == nil {
		return nil
	}
	out := new(QueryFrontendSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RetentionResolutionConfig) DeepCopyInto(out *RetentionResolutionConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RetentionResolutionConfig.
func (in *RetentionResolutionConfig) DeepCopy() *RetentionResolutionConfig {
	if in == nil {
		return nil
	}
	out := new(RetentionResolutionConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RouterSpec) DeepCopyInto(out *RouterSpec) {
	*out = *in
	in.CommonFields.DeepCopyInto(&out.CommonFields)
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.ExternalLabels != nil {
		in, out := &in.ExternalLabels, &out.ExternalLabels
		*out = make(ExternalLabels, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	in.Additional.DeepCopyInto(&out.Additional)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RouterSpec.
func (in *RouterSpec) DeepCopy() *RouterSpec {
	if in == nil {
		return nil
	}
	out := new(RouterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceMonitorConfig) DeepCopyInto(out *ServiceMonitorConfig) {
	*out = *in
	if in.Enable != nil {
		in, out := &in.Enable, &out.Enable
		*out = new(bool)
		**out = **in
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceMonitorConfig.
func (in *ServiceMonitorConfig) DeepCopy() *ServiceMonitorConfig {
	if in == nil {
		return nil
	}
	out := new(ServiceMonitorConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ShardingConfig) DeepCopyInto(out *ShardingConfig) {
	*out = *in
	if in.ExternalLabelSharding != nil {
		in, out := &in.ExternalLabelSharding, &out.ExternalLabelSharding
		*out = make([]ExternalLabelShardingConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ShardingConfig.
func (in *ShardingConfig) DeepCopy() *ShardingConfig {
	if in == nil {
		return nil
	}
	out := new(ShardingConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ShardingStrategy) DeepCopyInto(out *ShardingStrategy) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ShardingStrategy.
func (in *ShardingStrategy) DeepCopy() *ShardingStrategy {
	if in == nil {
		return nil
	}
	out := new(ShardingStrategy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StoreLimitsOptions) DeepCopyInto(out *StoreLimitsOptions) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StoreLimitsOptions.
func (in *StoreLimitsOptions) DeepCopy() *StoreLimitsOptions {
	if in == nil {
		return nil
	}
	out := new(StoreLimitsOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TSDBConfig) DeepCopyInto(out *TSDBConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TSDBConfig.
func (in *TSDBConfig) DeepCopy() *TSDBConfig {
	if in == nil {
		return nil
	}
	out := new(TSDBConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TelemetryQuantiles) DeepCopyInto(out *TelemetryQuantiles) {
	*out = *in
	if in.Duration != nil {
		in, out := &in.Duration, &out.Duration
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Samples != nil {
		in, out := &in.Samples, &out.Samples
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Series != nil {
		in, out := &in.Series, &out.Series
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TelemetryQuantiles.
func (in *TelemetryQuantiles) DeepCopy() *TelemetryQuantiles {
	if in == nil {
		return nil
	}
	out := new(TelemetryQuantiles)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TenancyConfig) DeepCopyInto(out *TenancyConfig) {
	*out = *in
	if in.Tenants != nil {
		in, out := &in.Tenants, &out.Tenants
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.TenantCertificateField != nil {
		in, out := &in.TenantCertificateField, &out.TenantCertificateField
		*out = new(string)
		**out = **in
	}
	if in.SplitTenantLabelName != nil {
		in, out := &in.SplitTenantLabelName, &out.SplitTenantLabelName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TenancyConfig.
func (in *TenancyConfig) DeepCopy() *TenancyConfig {
	if in == nil {
		return nil
	}
	out := new(TenancyConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ThanosCompact) DeepCopyInto(out *ThanosCompact) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ThanosCompact.
func (in *ThanosCompact) DeepCopy() *ThanosCompact {
	if in == nil {
		return nil
	}
	out := new(ThanosCompact)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ThanosCompact) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ThanosCompactList) DeepCopyInto(out *ThanosCompactList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ThanosCompact, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ThanosCompactList.
func (in *ThanosCompactList) DeepCopy() *ThanosCompactList {
	if in == nil {
		return nil
	}
	out := new(ThanosCompactList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ThanosCompactList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ThanosCompactSpec) DeepCopyInto(out *ThanosCompactSpec) {
	*out = *in
	in.CommonFields.DeepCopyInto(&out.CommonFields)
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	in.ObjectStorageConfig.DeepCopyInto(&out.ObjectStorageConfig)
	out.RetentionConfig = in.RetentionConfig
	if in.BlockConfig != nil {
		in, out := &in.BlockConfig, &out.BlockConfig
		*out = new(BlockConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.BlockViewerGlobalSync != nil {
		in, out := &in.BlockViewerGlobalSync, &out.BlockViewerGlobalSync
		*out = new(BlockViewerGlobalSyncConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.ShardingConfig != nil {
		in, out := &in.ShardingConfig, &out.ShardingConfig
		*out = new(ShardingConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.CompactConfig != nil {
		in, out := &in.CompactConfig, &out.CompactConfig
		*out = new(CompactConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.DownsamplingConfig != nil {
		in, out := &in.DownsamplingConfig, &out.DownsamplingConfig
		*out = new(DownsamplingConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.DebugConfig != nil {
		in, out := &in.DebugConfig, &out.DebugConfig
		*out = new(DebugConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.MinTime != nil {
		in, out := &in.MinTime, &out.MinTime
		*out = new(Duration)
		**out = **in
	}
	if in.MaxTime != nil {
		in, out := &in.MaxTime, &out.MaxTime
		*out = new(Duration)
		**out = **in
	}
	if in.Paused != nil {
		in, out := &in.Paused, &out.Paused
		*out = new(bool)
		**out = **in
	}
	if in.FeatureGates != nil {
		in, out := &in.FeatureGates, &out.FeatureGates
		*out = new(FeatureGates)
		(*in).DeepCopyInto(*out)
	}
	in.Additional.DeepCopyInto(&out.Additional)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ThanosCompactSpec.
func (in *ThanosCompactSpec) DeepCopy() *ThanosCompactSpec {
	if in == nil {
		return nil
	}
	out := new(ThanosCompactSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ThanosCompactStatus) DeepCopyInto(out *ThanosCompactStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ThanosCompactStatus.
func (in *ThanosCompactStatus) DeepCopy() *ThanosCompactStatus {
	if in == nil {
		return nil
	}
	out := new(ThanosCompactStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ThanosQuery) DeepCopyInto(out *ThanosQuery) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ThanosQuery.
func (in *ThanosQuery) DeepCopy() *ThanosQuery {
	if in == nil {
		return nil
	}
	out := new(ThanosQuery)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ThanosQuery) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ThanosQueryList) DeepCopyInto(out *ThanosQueryList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ThanosQuery, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ThanosQueryList.
func (in *ThanosQueryList) DeepCopy() *ThanosQueryList {
	if in == nil {
		return nil
	}
	out := new(ThanosQueryList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ThanosQueryList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ThanosQuerySpec) DeepCopyInto(out *ThanosQuerySpec) {
	*out = *in
	in.CommonFields.DeepCopyInto(&out.CommonFields)
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.ReplicaLabels != nil {
		in, out := &in.ReplicaLabels, &out.ReplicaLabels
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.StoreLabelSelector != nil {
		in, out := &in.StoreLabelSelector, &out.StoreLabelSelector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.TelemetryQuantiles != nil {
		in, out := &in.TelemetryQuantiles, &out.TelemetryQuantiles
		*out = new(TelemetryQuantiles)
		(*in).DeepCopyInto(*out)
	}
	if in.WebConfig != nil {
		in, out := &in.WebConfig, &out.WebConfig
		*out = new(WebConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.QueryFrontend != nil {
		in, out := &in.QueryFrontend, &out.QueryFrontend
		*out = new(QueryFrontendSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Paused != nil {
		in, out := &in.Paused, &out.Paused
		*out = new(bool)
		**out = **in
	}
	if in.FeatureGates != nil {
		in, out := &in.FeatureGates, &out.FeatureGates
		*out = new(FeatureGates)
		(*in).DeepCopyInto(*out)
	}
	in.Additional.DeepCopyInto(&out.Additional)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ThanosQuerySpec.
func (in *ThanosQuerySpec) DeepCopy() *ThanosQuerySpec {
	if in == nil {
		return nil
	}
	out := new(ThanosQuerySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ThanosQueryStatus) DeepCopyInto(out *ThanosQueryStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ThanosQueryStatus.
func (in *ThanosQueryStatus) DeepCopy() *ThanosQueryStatus {
	if in == nil {
		return nil
	}
	out := new(ThanosQueryStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ThanosReceive) DeepCopyInto(out *ThanosReceive) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ThanosReceive.
func (in *ThanosReceive) DeepCopy() *ThanosReceive {
	if in == nil {
		return nil
	}
	out := new(ThanosReceive)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ThanosReceive) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ThanosReceiveList) DeepCopyInto(out *ThanosReceiveList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ThanosReceive, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ThanosReceiveList.
func (in *ThanosReceiveList) DeepCopy() *ThanosReceiveList {
	if in == nil {
		return nil
	}
	out := new(ThanosReceiveList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ThanosReceiveList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ThanosReceiveSpec) DeepCopyInto(out *ThanosReceiveSpec) {
	*out = *in
	in.Router.DeepCopyInto(&out.Router)
	in.Ingester.DeepCopyInto(&out.Ingester)
	if in.Paused != nil {
		in, out := &in.Paused, &out.Paused
		*out = new(bool)
		**out = **in
	}
	if in.FeatureGates != nil {
		in, out := &in.FeatureGates, &out.FeatureGates
		*out = new(FeatureGates)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ThanosReceiveSpec.
func (in *ThanosReceiveSpec) DeepCopy() *ThanosReceiveSpec {
	if in == nil {
		return nil
	}
	out := new(ThanosReceiveSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ThanosReceiveStatus) DeepCopyInto(out *ThanosReceiveStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ThanosReceiveStatus.
func (in *ThanosReceiveStatus) DeepCopy() *ThanosReceiveStatus {
	if in == nil {
		return nil
	}
	out := new(ThanosReceiveStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ThanosRuler) DeepCopyInto(out *ThanosRuler) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ThanosRuler.
func (in *ThanosRuler) DeepCopy() *ThanosRuler {
	if in == nil {
		return nil
	}
	out := new(ThanosRuler)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ThanosRuler) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ThanosRulerList) DeepCopyInto(out *ThanosRulerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ThanosRuler, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ThanosRulerList.
func (in *ThanosRulerList) DeepCopy() *ThanosRulerList {
	if in == nil {
		return nil
	}
	out := new(ThanosRulerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ThanosRulerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ThanosRulerSpec) DeepCopyInto(out *ThanosRulerSpec) {
	*out = *in
	in.CommonFields.DeepCopyInto(&out.CommonFields)
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.QueryLabelSelector != nil {
		in, out := &in.QueryLabelSelector, &out.QueryLabelSelector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	in.ObjectStorageConfig.DeepCopyInto(&out.ObjectStorageConfig)
	if in.RuleConfigSelector != nil {
		in, out := &in.RuleConfigSelector, &out.RuleConfigSelector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.ExternalLabels != nil {
		in, out := &in.ExternalLabels, &out.ExternalLabels
		*out = make(ExternalLabels, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.AlertLabelDrop != nil {
		in, out := &in.AlertLabelDrop, &out.AlertLabelDrop
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Paused != nil {
		in, out := &in.Paused, &out.Paused
		*out = new(bool)
		**out = **in
	}
	if in.FeatureGates != nil {
		in, out := &in.FeatureGates, &out.FeatureGates
		*out = new(FeatureGates)
		(*in).DeepCopyInto(*out)
	}
	in.PrometheusRuleSelector.DeepCopyInto(&out.PrometheusRuleSelector)
	in.Additional.DeepCopyInto(&out.Additional)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ThanosRulerSpec.
func (in *ThanosRulerSpec) DeepCopy() *ThanosRulerSpec {
	if in == nil {
		return nil
	}
	out := new(ThanosRulerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ThanosRulerStatus) DeepCopyInto(out *ThanosRulerStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ThanosRulerStatus.
func (in *ThanosRulerStatus) DeepCopy() *ThanosRulerStatus {
	if in == nil {
		return nil
	}
	out := new(ThanosRulerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ThanosStore) DeepCopyInto(out *ThanosStore) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ThanosStore.
func (in *ThanosStore) DeepCopy() *ThanosStore {
	if in == nil {
		return nil
	}
	out := new(ThanosStore)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ThanosStore) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ThanosStoreList) DeepCopyInto(out *ThanosStoreList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ThanosStore, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ThanosStoreList.
func (in *ThanosStoreList) DeepCopy() *ThanosStoreList {
	if in == nil {
		return nil
	}
	out := new(ThanosStoreList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ThanosStoreList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ThanosStoreSpec) DeepCopyInto(out *ThanosStoreSpec) {
	*out = *in
	in.CommonFields.DeepCopyInto(&out.CommonFields)
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	in.ObjectStorageConfig.DeepCopyInto(&out.ObjectStorageConfig)
	if in.IndexCacheConfig != nil {
		in, out := &in.IndexCacheConfig, &out.IndexCacheConfig
		*out = new(CacheConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.CachingBucketConfig != nil {
		in, out := &in.CachingBucketConfig, &out.CachingBucketConfig
		*out = new(CacheConfig)
		(*in).DeepCopyInto(*out)
	}
	out.ShardingStrategy = in.ShardingStrategy
	if in.MinTime != nil {
		in, out := &in.MinTime, &out.MinTime
		*out = new(Duration)
		**out = **in
	}
	if in.MaxTime != nil {
		in, out := &in.MaxTime, &out.MaxTime
		*out = new(Duration)
		**out = **in
	}
	if in.StoreLimitsOptions != nil {
		in, out := &in.StoreLimitsOptions, &out.StoreLimitsOptions
		*out = new(StoreLimitsOptions)
		**out = **in
	}
	if in.IndexHeaderConfig != nil {
		in, out := &in.IndexHeaderConfig, &out.IndexHeaderConfig
		*out = new(IndexHeaderConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.BlockConfig != nil {
		in, out := &in.BlockConfig, &out.BlockConfig
		*out = new(BlockConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Paused != nil {
		in, out := &in.Paused, &out.Paused
		*out = new(bool)
		**out = **in
	}
	if in.FeatureGates != nil {
		in, out := &in.FeatureGates, &out.FeatureGates
		*out = new(FeatureGates)
		(*in).DeepCopyInto(*out)
	}
	in.Additional.DeepCopyInto(&out.Additional)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ThanosStoreSpec.
func (in *ThanosStoreSpec) DeepCopy() *ThanosStoreSpec {
	if in == nil {
		return nil
	}
	out := new(ThanosStoreSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ThanosStoreStatus) DeepCopyInto(out *ThanosStoreStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ThanosStoreStatus.
func (in *ThanosStoreStatus) DeepCopy() *ThanosStoreStatus {
	if in == nil {
		return nil
	}
	out := new(ThanosStoreStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WebConfig) DeepCopyInto(out *WebConfig) {
	*out = *in
	if in.RoutePrefix != nil {
		in, out := &in.RoutePrefix, &out.RoutePrefix
		*out = new(string)
		**out = **in
	}
	if in.ExternalPrefix != nil {
		in, out := &in.ExternalPrefix, &out.ExternalPrefix
		*out = new(string)
		**out = **in
	}
	if in.PrefixHeader != nil {
		in, out := &in.PrefixHeader, &out.PrefixHeader
		*out = new(string)
		**out = **in
	}
	if in.DisableCORS != nil {
		in, out := &in.DisableCORS, &out.DisableCORS
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WebConfig.
func (in *WebConfig) DeepCopy() *WebConfig {
	if in == nil {
		return nil
	}
	out := new(WebConfig)
	in.DeepCopyInto(out)
	return out
}
