[build]
  publish = "public"
  functions = "functions"

[build.environment]
  NODE_VERSION = "20.11.0"
  NPM_VERSION = "10.2.4"
  HUGO_VERSION = "0.145.0+extended+withdeploy"
  HUGO_ENV = "production"

[context.production]
  command = "make website"

[context.deploy-preview]
  command = "make website"

[context.branch-deploy]
  command = "make website"

[context.next]
  command = "make website"

[context.next.environment]
  HUGO_ENV = "next"

[dev]
  framework = "#custom"
  command = "make website-dev"
  targetPort = 1313
  port = 8888
  publish = "public"
  autoLaunch = false

# Redirects and rewrites — https://docs.netlify.com/routing/redirects/#syntax-for-the-netlify-configuration-file

# Common redirects for user convenience
[[redirects]]
  from = "/docs/"
  to = "/docs/guides/get-started/"
  status = 302

[[redirects]]
  from = "/guides/"
  to = "/docs/guides/"
  status = 302

[[redirects]]
  from = "/contributing/"
  to = "/docs/community/contributing/"
  status = 302

[[redirects]]
  from = "/installation/"
  to = "/docs/guides/installation/"
  status = 302

[[redirects]]
  from = "/docs/design/"
  to = "/docs/guides/design/"
  status = 301

# Custom headers — https://docs.netlify.com/routing/headers/#syntax-for-the-netlify-configuration-file
[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = "default-src 'self'; manifest-src 'self'; connect-src 'self'; font-src 'self'; img-src 'self' https://avatars.githubusercontent.com data:; script-src 'self' 'nonce-dXNlcj0iaGVsbG8iLGRvbWFpbj0iaGVua3ZlcmxpbmRlLmNvbSIsZG9jdW1lbnQud3JpdGUodXNlcisiQCIrZG9tYWluKTs=' 'sha256-aWZ3y/RxbBYKHXH0z8+8ljrHG1mSBvyzSfxSMjBSaXk='; style-src 'self'"
    X-Frame-Options = "SAMEORIGIN"
    Referrer-Policy = "strict-origin"
    Permissions-Policy = "geolocation=(self), microphone=(), camera=()"
    Cache-Control= '''
    public,
    max-age=31536000'''
    Access-Control-Allow-Origin = "*"
