name: Build and Push Multi-Platform Image to Quay

on:
  push:
    branches:
      - 'master'
      - 'main'
    tags:
      - 'v*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Quay
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache for Docker's buildx
        uses: actions/cache@v4
        with:
          path: .buildxcache/
          key: ${{ runner.os }}-buildx-${{ hashFiles('**/*.go', 'Dockerfile', 'go.sum') }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build and push multi-platform image
        run: make docker-buildx 
